// Auto-generated by scripts/build.mjs — do not edit manually
// Built: 2026-07-08T01:33:56.279Z

window.__BUILD_TIMESTAMP = "2026-07-08T01:33:56.279Z";

window.__ROUTE_MAP = {
  "#linux-cli-basics": "content/linux/foundations/linux-cli-basics.json",
  "#linux-filesystem": "content/linux/foundations/linux-filesystem.json",
  "#linux-git": "content/linux/foundations/linux-git.json",
  "#linux-history": "content/linux/foundations/linux-history.json",
  "#linux-networking": "content/linux/systems/linux-networking.json",
  "#linux-package-mgmt": "content/linux/systems/linux-package-mgmt.json",
  "#linux-permissions": "content/linux/foundations/linux-permissions.json",
  "#linux-processes": "content/linux/systems/linux-processes.json",
  "#linux-shell-basics": "content/linux/foundations/linux-shell-basics.json",
  "#linux-ssh": "content/linux/systems/linux-ssh.json",
  "#linux-storage": "content/linux/systems/linux-storage.json",
  "#linux-systemd": "content/linux/systems/linux-systemd.json",
  "#linux-text-processing": "content/linux/foundations/linux-text-processing.json",
  "#linux-users-groups": "content/linux/systems/linux-users-groups.json",
};

window.__SEARCH_INDEX = [
  {
    "title": "CLI Fundamentals",
    "category": "Linux",
    "url": "docs.html#linux-cli-basics",
    "tags": [
      "FAANG",
      "Linux",
      "CLI",
      "basics",
      "interview"
    ],
    "description": "The Linux command line is the primary interface for every engineer at FAANG. GUI tools are rarely used in production. This guide covers the essential…",
    "sections": [
      "The Unix Philosophy: Small Composable Tools",
      "Essential Commands Every FAANG Engineer Knows Cold",
      "I/O Redirection & Here Documents",
      "Environment Variables & Shell Configuration",
      "Job Control & Process Management",
      "FAANG Interview Q&A",
      "References & Further Reading"
    ]
  },
  {
    "title": "Filesystem Hierarchy Standard",
    "category": "Linux",
    "url": "docs.html#linux-filesystem",
    "tags": [
      "FAANG",
      "Linux",
      "filesystem",
      "interview"
    ],
    "description": "The Filesystem Hierarchy Standard (FHS) defines the directory structure on Linux systems. Knowing where things live — and why — is table-stakes for…",
    "sections": [
      "The Root Filesystem (/)",
      "/etc — The Configuration Nerve Center",
      "/proc & /sys — Virtual Filesystems for Kernel Introspection",
      "/var — Variable Data (Logs, Databases, Spool)",
      "FAANG Interview Q&A",
      "References & Further Reading"
    ]
  },
  {
    "title": "Git Version Control",
    "category": "Linux",
    "url": "docs.html#linux-git",
    "tags": [
      "FAANG",
      "Linux",
      "git",
      "version-control",
      "interview"
    ],
    "description": "Git is the version control system that underpins all modern software development. Created by Linus Torvalds for Linux kernel development, Git is now…",
    "sections": [
      "Git Objects: Blobs, Trees, Commits",
      "Branching & Merging Strategies",
      "Interactive Rebase & History Rewriting",
      "Git in Production: The FAANG Workflow",
      "Git Configuration & Productivity Tips",
      "FAANG Interview Q&A",
      "References & Further Reading"
    ]
  },
  {
    "title": "History of Linux & Unix",
    "category": "Linux",
    "url": "docs.html#linux-history",
    "tags": [
      "FAANG",
      "Linux",
      "history",
      "interview"
    ],
    "description": "Linux is the dominant operating system powering 96% of the top 1M web servers, all Android devices, 100% of the TOP500 supercomputers, and the…",
    "sections": []
  },
  {
    "title": "File Permissions & ACLs",
    "category": "Linux",
    "url": "docs.html#linux-permissions",
    "tags": [
      "FAANG",
      "Linux",
      "permissions",
      "security",
      "interview"
    ],
    "description": "Linux file permissions are the foundation of system security. Every FAANG SRE and infrastructure engineer must understand the permission model cold —…",
    "sections": [
      "The Permission Triplet: Owner-Group-Other",
      "Directories: Execute Bit = Traversal",
      "Special Permissions: SUID, SGID, Sticky Bit",
      "Access Control Lists (ACLs)",
      "umask & Default Permissions",
      "FAANG Interview Q&A",
      "References & Further Reading"
    ]
  },
  {
    "title": "Shell Scripting Basics",
    "category": "Linux",
    "url": "docs.html#linux-shell-basics",
    "tags": [
      "FAANG",
      "Linux",
      "shell-scripting",
      "bash",
      "interview"
    ],
    "description": "Shell scripting is how Linux systems are automated. From CI/CD pipelines to deployment scripts to cron jobs — if you work at FAANG, you will read and…",
    "sections": [
      "Script Anatomy & Shebang",
      "Variables, Parameters & Quoting",
      "Conditionals & Control Flow",
      "Loops & Arrays",
      "Functions & Error Handling",
      "FAANG Interview Q&A",
      "References & Further Reading"
    ]
  },
  {
    "title": "Text Processing: grep, sed, awk",
    "category": "Linux",
    "url": "docs.html#linux-text-processing",
    "tags": [
      "FAANG",
      "Linux",
      "text-processing",
      "grep",
      "sed",
      "awk",
      "interview"
    ],
    "description": "grep, sed, and awk are the three pillars of Linux text processing. At FAANG, every engineer — from SRE to ML researcher — uses these tools daily.…",
    "sections": [
      "grep — Global Regular Expression Print",
      "sed — Stream Editor",
      "awk — Pattern Scanning and Processing Language",
      "xargs — Build and Execute Commands",
      "Pipeline-Fu: Combining Everything",
      "FAANG Interview Q&A",
      "References & Further Reading"
    ]
  },
  {
    "title": "Linux Networking",
    "category": "Linux",
    "url": "docs.html#linux-networking",
    "tags": [
      "FAANG",
      "Linux",
      "networking",
      "tcpdump",
      "DNS",
      "iptables",
      "troubleshooting"
    ],
    "description": "Linux networking is a vast topic that every infrastructure engineer must understand. From interface configuration to packet filtering, DNS resolution…",
    "sections": [
      "Network Interfaces & Configuration",
      "Socket Diagnostics: ss, netstat & lsof",
      "DNS Resolution on Linux",
      "Packet Filtering: iptables & nftables",
      "Packet Capture: tcpdump & wireshark",
      "FAANG Interview Q&A",
      "References & Further Reading"
    ]
  },
  {
    "title": "Package Management",
    "category": "Linux",
    "url": "docs.html#linux-package-mgmt",
    "tags": [
      "FAANG",
      "Linux",
      "apt",
      "yum",
      "dnf",
      "package management",
      "containers"
    ],
    "description": "Package management is how Linux systems install, update, and remove software. At FAANG, you'll work across Debian-based (Ubuntu), RHEL-based (Amazon…",
    "sections": [
      "Debian/Ubuntu: APT & dpkg",
      "RHEL/CentOS/Amazon Linux: RPM & YUM/DNF",
      "Compiling from Source & Alternatives",
      "Docker & Containers: The Modern \"Package\"",
      "FAANG Interview Q&A",
      "References & Further Reading"
    ]
  },
  {
    "title": "Process Management & Signals",
    "category": "Linux",
    "url": "docs.html#linux-processes",
    "tags": [
      "FAANG",
      "Linux",
      "processes",
      "signals",
      "cgroups",
      "production debugging"
    ],
    "description": "Processes are the fundamental unit of execution on Linux. Every program, daemon, and shell command runs as one or more processes. At FAANG,…",
    "sections": [
      "Process Lifecycle & States",
      "Signals: The Linux Interrupt System",
      "Daemons & Process Supervision",
      "cgroups & Containers (Modern Process Isolation)",
      "FAANG Interview Q&A",
      "References & Further Reading"
    ]
  },
  {
    "title": "SSH: Secure Shell",
    "category": "Linux",
    "url": "docs.html#linux-ssh",
    "tags": [
      "FAANG",
      "Linux",
      "SSH",
      "security",
      "tunneling",
      "authentication"
    ],
    "description": "SSH (Secure Shell) is the universal protocol for remote access to Linux systems. Despite the rise of 'no-SSH' architectures (immutable…",
    "sections": [
      "SSH Authentication: Keys, Certificates & Agents",
      "SSH Client Configuration (~/.ssh/config)",
      "SSH Server Hardening",
      "SSH Tunneling & Port Forwarding",
      "SSH Troubleshooting & Debugging",
      "FAANG Interview Q&A",
      "References & Further Reading"
    ]
  },
  {
    "title": "Storage, Filesystems & Disk Management",
    "category": "Linux",
    "url": "docs.html#linux-storage",
    "tags": [
      "FAANG",
      "Linux",
      "storage",
      "filesystem",
      "LVM",
      "disk management",
      "monitoring"
    ],
    "description": "Storage on Linux spans a hierarchy: physical disks → partitions → LVM (logical volumes) → filesystems → mount points. At FAANG, storage is abstracted…",
    "sections": [
      "Disk Discovery & Partitioning",
      "Filesystems: ext4, XFS & Modern Options",
      "Mounting & /etc/fstab",
      "LVM: Logical Volume Manager",
      "Monitoring: I/O, Space & Inodes",
      "FAANG Interview Q&A",
      "References & Further Reading"
    ]
  },
  {
    "title": "systemd: The Modern Init System",
    "category": "Linux",
    "url": "docs.html#linux-systemd",
    "tags": [
      "FAANG",
      "Linux",
      "systemd",
      "journald",
      "init",
      "service management"
    ],
    "description": "systemd is the init system and service manager for virtually every modern Linux distribution. It replaced SysV init and handles service startup,…",
    "sections": [
      "Core Concepts: Units & Targets",
      "Writing a Service Unit File",
      "journalctl: The systemd Logging System",
      "Timers (Replacing Cron) & Socket Activation",
      "System Analysis & Debugging",
      "FAANG Interview Q&A",
      "References & Further Reading"
    ]
  },
  {
    "title": "Users, Groups & Authentication",
    "category": "Linux",
    "url": "docs.html#linux-users-groups",
    "tags": [
      "FAANG",
      "Linux",
      "users",
      "groups",
      "sudo",
      "PAM",
      "authentication",
      "security"
    ],
    "description": "Linux is a multi-user operating system from the ground up. Every process runs as a specific user, every file has an owner and group, and access…",
    "sections": [
      "User & Group Fundamentals",
      "sudo: Delegated Privilege",
      "PAM: Pluggable Authentication Modules",
      "Service Accounts & Least Privilege",
      "FAANG Interview Q&A",
      "References & Further Reading"
    ]
  }
];
