// Auto-generated by scripts/build.mjs — do not edit manually
// Built: 2026-07-08T04:34:00.132Z

window.__BUILD_TIMESTAMP = "2026-07-08T04:34:00.132Z";

window.__ROUTE_MAP = {
  "#linux-bpf": "content/linux/advanced/linux-bpf.json",
  "#linux-build-toolchain": "content/linux/advanced/linux-build-toolchain.json",
  "#linux-cgroups": "content/linux/sre/linux-cgroups.json",
  "#linux-cli-basics": "content/linux/foundations/linux-cli-basics.json",
  "#linux-docker": "content/linux/sre/linux-docker.json",
  "#linux-faang-scale": "content/linux/sre/linux-faang-scale.json",
  "#linux-filesystem": "content/linux/foundations/linux-filesystem.json",
  "#linux-git": "content/linux/foundations/linux-git.json",
  "#linux-gpu-computing": "content/linux/advanced/linux-gpu-computing.json",
  "#linux-history": "content/linux/foundations/linux-history.json",
  "#linux-interview-qs": "content/linux/sre/linux-interview-qs.json",
  "#linux-io": "content/linux/advanced/linux-io.json",
  "#linux-kernel": "content/linux/advanced/linux-kernel.json",
  "#linux-kubernetes": "content/linux/sre/linux-kubernetes.json",
  "#linux-memory": "content/linux/advanced/linux-memory.json",
  "#linux-monitoring": "content/linux/advanced/linux-monitoring.json",
  "#linux-networking": "content/linux/systems/linux-networking.json",
  "#linux-package-mgmt": "content/linux/systems/linux-package-mgmt.json",
  "#linux-perf": "content/linux/advanced/linux-perf.json",
  "#linux-permissions": "content/linux/foundations/linux-permissions.json",
  "#linux-processes": "content/linux/systems/linux-processes.json",
  "#linux-security": "content/linux/sre/linux-security.json",
  "#linux-shell-basics": "content/linux/foundations/linux-shell-basics.json",
  "#linux-ssh": "content/linux/systems/linux-ssh.json",
  "#linux-storage": "content/linux/systems/linux-storage.json",
  "#linux-system-rescue": "content/linux/sre/linux-system-rescue.json",
  "#linux-systemd": "content/linux/systems/linux-systemd.json",
  "#linux-text-processing": "content/linux/foundations/linux-text-processing.json",
  "#linux-troubleshooting": "content/linux/sre/linux-troubleshooting.json",
  "#linux-users": "content/linux/systems/linux-users.json",
};

window.__SEARCH_INDEX = [
  {
    "title": "BPF & eBPF Deep Dive",
    "category": "Linux",
    "url": "docs.html#linux-bpf",
    "tags": [
      "faang-insight",
      "Linux",
      "eBPF",
      "BPF",
      "bpftrace",
      "bcc",
      "XDP",
      "observability",
      "networking"
    ],
    "description": "BPF (Berkeley Packet Filter), evolved into eBPF (extended BPF), is a revolutionary kernel technology that allows running sandboxed programs in the…",
    "sections": [
      "eBPF Architecture & Concepts",
      "bpftrace: High-Level eBPF Tracing",
      "bcc: The BPF Compiler Collection",
      "XDP & eBPF Networking",
      "Interview Q&A",
      "References & Further Reading"
    ],
    "difficulty": "advanced",
    "readingTime": 16,
    "prerequisites": [
      "linux-kernel",
      "linux-networking"
    ]
  },
  {
    "title": "Linux Build & Toolchain",
    "category": "Linux",
    "url": "docs.html#linux-build-toolchain",
    "tags": [
      "faang-insight",
      "Linux",
      "build",
      "toolchain",
      "compiler",
      "linker",
      "Bazel",
      "optimization"
    ],
    "description": "Every engineer compiles code — but understanding the toolchain (compiler, linker, loader, libraries, build systems) separates those who debug build…",
    "sections": [
      "The C Compilation Pipeline",
      "Shared Libraries: SONAME, RPATH & LD_LIBRARY_PATH",
      "Build Systems: Make, CMake, Bazel & Hermetic Builds",
      "LTO, PGO & Binary Optimization",
      "Interview Q&A",
      "References & Further Reading"
    ],
    "difficulty": "advanced",
    "readingTime": 17,
    "prerequisites": [
      "linux-cli-basics",
      "linux-shell-basics",
      "linux-git"
    ]
  },
  {
    "title": "GPU Computing on Linux",
    "category": "Linux",
    "url": "docs.html#linux-gpu-computing",
    "tags": [
      "faang-insight",
      "Linux",
      "GPU",
      "CUDA",
      "NVIDIA",
      "MIG",
      "machine learning",
      "profiling"
    ],
    "description": "GPU computing on Linux is the backbone of ML/AI at Enterprise. Understanding the GPU driver stack — from kernel modules to CUDA runtime to container…",
    "sections": [
      "GPU Stack: From Kernel to Application",
      "GPU Performance & Profiling",
      "GPU Multi-Tenancy: MIG, Time-Slicing & MPS",
      "NVIDIA Container Toolkit & Kubernetes GPU",
      "Interview Q&A",
      "References & Further Reading"
    ],
    "difficulty": "advanced",
    "readingTime": 17,
    "prerequisites": [
      "linux-kernel",
      "linux-memory"
    ]
  },
  {
    "title": "I/O Stack & Filesystem Performance",
    "category": "Linux",
    "url": "docs.html#linux-io",
    "tags": [
      "faang-insight",
      "Linux",
      "I/O",
      "storage performance",
      "filesystem",
      "iostat",
      "benchmarking"
    ],
    "description": "The Linux I/O stack spans multiple layers: application → syscall → VFS → filesystem → block layer → I/O scheduler → device driver → disk hardware. At…",
    "sections": [
      "The Linux I/O Stack",
      "Measure I/O Latency & Throughput",
      "Filesystem Performance Tuning",
      "Storage Performance at Enterprise scale",
      "Interview Q&A",
      "References & Further Reading"
    ],
    "difficulty": "advanced",
    "readingTime": 18,
    "prerequisites": [
      "linux-kernel",
      "linux-storage"
    ]
  },
  {
    "title": "Kernel Architecture & Syscalls",
    "category": "Linux",
    "url": "docs.html#linux-kernel",
    "tags": [
      "faang-insight",
      "Linux",
      "kernel",
      "syscalls",
      "scheduler",
      "kernel modules"
    ],
    "description": "The Linux kernel is the core of the operating system — it manages processes, memory, hardware, and provides the syscall interface that user-space…",
    "sections": [
      "Kernel Architecture: User Space vs Kernel Space",
      "System Calls Deep Dive",
      "The Kernel Scheduler & Context Switching",
      "Kernel Modules & Device Drivers",
      "Interview Q&A",
      "References & Further Reading"
    ],
    "difficulty": "advanced",
    "readingTime": 17,
    "prerequisites": [
      "linux-processes",
      "linux-memory"
    ]
  },
  {
    "title": "Memory Management & OOM Handling",
    "category": "Linux",
    "url": "docs.html#linux-memory",
    "tags": [
      "faang-insight",
      "Linux",
      "memory",
      "OOM",
      "page cache",
      "huge pages",
      "performance"
    ],
    "description": "Memory management is one of the most critical subsystems in Linux. The kernel manages physical RAM, virtual address spaces, page caches, swapping,…",
    "sections": [
      "Virtual Memory & Address Spaces",
      "Page Cache & Buffers",
      "OOM Killer: Out-Of-Memory Management",
      "Huge Pages & Memory Performance",
      "Interview Q&A",
      "References & Further Reading"
    ],
    "difficulty": "advanced",
    "readingTime": 19,
    "prerequisites": [
      "linux-kernel",
      "linux-processes"
    ]
  },
  {
    "title": "Monitoring & Observability",
    "category": "Linux",
    "url": "docs.html#linux-monitoring",
    "tags": [
      "faang-insight",
      "Linux",
      "monitoring",
      "observability",
      "Prometheus",
      "logging",
      "SRE"
    ],
    "description": "Monitoring and observability are how you understand what your systems are doing. Monitoring tells you something is wrong; observability lets you ask…",
    "sections": [
      "The Three Pillars: Metrics, Logs, Traces",
      "Prometheus & Node Exporter",
      "Logging: journald, syslog & Logrotate",
      "Distributed Tracing & Observability Concepts",
      "Interview Q&A",
      "References & Further Reading"
    ],
    "difficulty": "advanced",
    "readingTime": 16,
    "prerequisites": [
      "linux-processes",
      "linux-networking",
      "linux-systemd"
    ]
  },
  {
    "title": "Performance Tuning & Profiling",
    "category": "Linux",
    "url": "docs.html#linux-perf",
    "tags": [
      "faang-insight",
      "Linux",
      "perf",
      "profiling",
      "performance",
      "ftrace",
      "flamegraphs"
    ],
    "description": "Performance tuning is the art of identifying and eliminating bottlenecks. Linux provides powerful tools — perf, flamegraphs, ftrace, and BPF — for…",
    "sections": [
      "perf: The Universal Profiler",
      "Brendan Gregg's USE Method & Methodology",
      "ftrace: Kernel Function Tracing",
      "CPU & Memory Profiling in Practice",
      "Interview Q&A",
      "References & Further Reading"
    ],
    "difficulty": "advanced",
    "readingTime": 16,
    "prerequisites": [
      "linux-kernel",
      "linux-memory",
      "linux-processes"
    ]
  },
  {
    "title": "CLI Fundamentals",
    "category": "Linux",
    "url": "docs.html#linux-cli-basics",
    "tags": [
      "faang-insight",
      "Linux",
      "CLI",
      "basics",
      "interview"
    ],
    "description": "The Linux command line is the primary interface for every engineer at Enterprise. GUI tools are rarely used in production. This guide covers the…",
    "sections": [
      "The Unix Philosophy: Small Composable Tools",
      "Essential Commands Every Production engineers Knows Cold",
      "I/O Redirection & Here Documents",
      "Environment Variables & Shell Configuration",
      "Job Control & Process Management",
      "Interview Q&A",
      "References & Further Reading"
    ],
    "difficulty": "beginner",
    "readingTime": 17,
    "prerequisites": [
      "linux-history"
    ]
  },
  {
    "title": "Filesystem Hierarchy Standard",
    "category": "Linux",
    "url": "docs.html#linux-filesystem",
    "tags": [
      "faang-insight",
      "Linux",
      "filesystem",
      "interview"
    ],
    "description": "The Filesystem Hierarchy Standard (FHS) defines the directory structure on Linux systems. Knowing where things live — and why — is table-stakes for…",
    "sections": [
      "The Root Filesystem (/)",
      "/etc — The Configuration Nerve Center",
      "/proc & /sys — Virtual Filesystems for Kernel Introspection",
      "/var — Variable Data (Logs, Databases, Spool)",
      "Interview Q&A",
      "References & Further Reading"
    ],
    "difficulty": "beginner",
    "readingTime": 15,
    "prerequisites": [
      "linux-history"
    ]
  },
  {
    "title": "Git Version Control",
    "category": "Linux",
    "url": "docs.html#linux-git",
    "tags": [
      "faang-insight",
      "Linux",
      "git",
      "version-control",
      "interview"
    ],
    "description": "Git is the version control system that underpins all modern software development. Created by Linus Torvalds for Linux kernel development, Git is now…",
    "sections": [
      "Git Objects: Blobs, Trees, Commits",
      "Branching & Merging Strategies",
      "Interactive Rebase & History Rewriting",
      "Git in Production: The Enterprise Workflow",
      "Git Configuration & Productivity Tips",
      "Interview Q&A",
      "References & Further Reading"
    ],
    "difficulty": "advanced",
    "readingTime": 17,
    "prerequisites": [
      "linux-cli-basics"
    ]
  },
  {
    "title": "History of Linux & Unix",
    "category": "Linux",
    "url": "docs.html#linux-history",
    "tags": [
      "faang-insight",
      "Linux",
      "history",
      "interview"
    ],
    "description": "Linux is the dominant operating system powering 96% of the top 1M web servers, all Android devices, 100% of the TOP500 supercomputers, and the…",
    "sections": [],
    "difficulty": "beginner",
    "readingTime": 5,
    "prerequisites": []
  },
  {
    "title": "File Permissions & ACLs",
    "category": "Linux",
    "url": "docs.html#linux-permissions",
    "tags": [
      "faang-insight",
      "Linux",
      "permissions",
      "security",
      "interview"
    ],
    "description": "Linux file permissions are the foundation of system security. Every Production SRE and infrastructure engineer must understand the permission model…",
    "sections": [
      "The Permission Triplet: Owner-Group-Other",
      "Directories: Execute Bit = Traversal",
      "Special Permissions: SUID, SGID, Sticky Bit",
      "Access Control Lists (ACLs)",
      "umask & Default Permissions",
      "Interview Q&A",
      "References & Further Reading"
    ],
    "difficulty": "advanced",
    "readingTime": 17,
    "prerequisites": [
      "linux-filesystem",
      "linux-cli-basics"
    ]
  },
  {
    "title": "Shell Scripting Basics",
    "category": "Linux",
    "url": "docs.html#linux-shell-basics",
    "tags": [
      "faang-insight",
      "Linux",
      "shell-scripting",
      "bash",
      "interview"
    ],
    "description": "Shell scripting is how Linux systems are automated. From CI/CD pipelines to deployment scripts to cron jobs — if you work at Enterprise, you will…",
    "sections": [
      "Script Anatomy & Shebang",
      "Variables, Parameters & Quoting",
      "Conditionals & Control Flow",
      "Loops & Arrays",
      "Functions & Error Handling",
      "Interview Q&A",
      "References & Further Reading"
    ],
    "difficulty": "beginner",
    "readingTime": 18,
    "prerequisites": [
      "linux-cli-basics"
    ]
  },
  {
    "title": "Text Processing: grep, sed, awk",
    "category": "Linux",
    "url": "docs.html#linux-text-processing",
    "tags": [
      "faang-insight",
      "Linux",
      "text-processing",
      "grep",
      "sed",
      "awk",
      "interview"
    ],
    "description": "grep, sed, and awk are the three pillars of Linux text processing. At Enterprise, every engineer — from SRE to ML researcher — uses these tools…",
    "sections": [
      "grep — Global Regular Expression Print",
      "sed — Stream Editor",
      "awk — Pattern Scanning and Processing Language",
      "xargs — Build and Execute Commands",
      "Pipeline-Fu: Combining Everything",
      "Interview Q&A",
      "References & Further Reading"
    ],
    "difficulty": "beginner",
    "readingTime": 17,
    "prerequisites": [
      "linux-cli-basics",
      "linux-shell-basics"
    ]
  },
  {
    "title": "cgroups & Namespaces",
    "category": "Linux",
    "url": "docs.html#linux-cgroups",
    "tags": [
      "faang-insight",
      "Linux",
      "cgroups",
      "namespaces",
      "containers",
      "Docker",
      "Kubernetes"
    ],
    "description": "Control groups (cgroups) and namespaces are the two Linux kernel features that make containers possible. cgroups limit resource usage (CPU, memory,…",
    "sections": [
      "Namespaces: The Illusion of Isolation",
      "cgroups v2: Resource Accounting & Limiting",
      "Docker & Containers: cgroups + Namespaces in Practice",
      "Debugging Resource Issues with cgroups",
      "Interview Q&A",
      "References & Further Reading"
    ],
    "difficulty": "intermediate",
    "readingTime": 19,
    "prerequisites": [
      "linux-processes",
      "linux-kernel"
    ]
  },
  {
    "title": "Docker & Container Lifecycle",
    "category": "Linux",
    "url": "docs.html#linux-docker",
    "tags": [
      "faang-insight",
      "Linux",
      "Docker",
      "containers",
      "OCI",
      "container lifecycle"
    ],
    "description": "Docker is the most widely used container runtime, built on Linux cgroups and namespaces. At Enterprise, Docker (or its OCI-compatible alternatives…",
    "sections": [
      "Container Images: Layers & Build Caching",
      "Container Runtime & Lifecycle",
      "Networking & Storage in Docker",
      "Debugging Containers",
      "Interview Q&A",
      "References & Further Reading"
    ],
    "difficulty": "intermediate",
    "readingTime": 17,
    "prerequisites": [
      "linux-cgroups",
      "linux-networking",
      "linux-filesystem"
    ]
  },
  {
    "title": "Linux at Enterprise scale",
    "category": "Linux",
    "url": "docs.html#linux-faang-scale",
    "tags": [
      "faang-insight",
      "Linux",
      "fleet management",
      "Golden AMI",
      "capacity planning",
      "SRE",
      "scale"
    ],
    "description": "Running Linux on 10,000+ servers is fundamentally different from running Linux on one server. At Enterprise, every Linux concern — kernel versions,…",
    "sections": [
      "The Golden AMI Pipeline",
      "Kernel Management at Scale",
      "Observability Infrastructure",
      "Capacity Planning & Linux Resource Management",
      "Interview Q&A",
      "References & Further Reading"
    ],
    "difficulty": "intermediate",
    "readingTime": 19,
    "prerequisites": [
      "linux-kernel",
      "linux-networking",
      "linux-monitoring",
      "linux-docker"
    ]
  },
  {
    "title": "Linux Interview Q&A",
    "category": "Linux",
    "url": "docs.html#linux-interview-qs",
    "tags": [
      "faang-insight",
      "Linux",
      "interview",
      "preparation",
      "system design",
      "debugging"
    ],
    "description": "Linux knowledge is tested throughout the Interview process — from initial phone screens to system design to on-site 'bar raiser' rounds. This guide…",
    "sections": [
      "Role-Specific Linux Expectations",
      "Common Interview Questions by Topic",
      "System Design with Linux Constraints",
      "Common Pitfalls & Anti-Patterns",
      "References & Further Reading"
    ],
    "difficulty": "intermediate",
    "readingTime": 16,
    "prerequisites": []
  },
  {
    "title": "Kubernetes for Linux Engineers",
    "category": "Linux",
    "url": "docs.html#linux-kubernetes",
    "tags": [
      "faang-insight",
      "Linux",
      "Kubernetes",
      "kubelet",
      "CRI",
      "CNI",
      "CSI",
      "containers",
      "eBPF"
    ],
    "description": "Kubernetes is a Linux cluster operating system. Every Kubernetes node runs Linux, and every container is a Linux process. Understanding Kubernetes…",
    "sections": [
      "Kubelet: The Node Agent",
      "CRI: Container Runtime Interface",
      "CNI: Container Networking Interface",
      "CSI: Container Storage Interface",
      "Interview Q&A",
      "References & Further Reading"
    ],
    "difficulty": "advanced",
    "readingTime": 17,
    "prerequisites": [
      "linux-docker",
      "linux-networking",
      "linux-systemd"
    ]
  },
  {
    "title": "Security Hardening",
    "category": "Linux",
    "url": "docs.html#linux-security",
    "tags": [
      "faang-insight",
      "Linux",
      "security",
      "SELinux",
      "AppArmor",
      "seccomp",
      "auditd",
      "hardening"
    ],
    "description": "Linux security is defense in depth: from kernel hardening (SELinux, AppArmor, seccomp) to system configuration (sysctl, PAM, auditd) to operational…",
    "sections": [
      "Kernel Hardening: sysctl Security Settings",
      "Seccomp: Secure Computing Mode",
      "SELinux & AppArmor",
      "Auditd: Linux Audit System",
      "Interview Q&A",
      "References & Further Reading"
    ],
    "difficulty": "intermediate",
    "readingTime": 17,
    "prerequisites": [
      "linux-users",
      "linux-permissions",
      "linux-networking",
      "linux-systemd"
    ]
  },
  {
    "title": "System Rescue & Recovery",
    "category": "Linux",
    "url": "docs.html#linux-system-rescue",
    "tags": [
      "faang-insight",
      "Linux",
      "recovery",
      "GRUB",
      "chroot",
      "rescue",
      "filesystem repair"
    ],
    "description": "Every senior engineer faces an unbootable server, a corrupt filesystem, or a forgotten root password at some point. System rescue skills — the…",
    "sections": [
      "Boot Process: From Power-On to Login Prompt",
      "GRUB: Bootloader Rescue & Repair",
      "Chroot Rescue & Single-User Mode",
      "Filesystem Recovery & Data Rescue",
      "Interview Q&A",
      "References & Further Reading"
    ],
    "difficulty": "intermediate",
    "readingTime": 18,
    "prerequisites": [
      "linux-troubleshooting",
      "linux-storage",
      "linux-filesystem"
    ]
  },
  {
    "title": "Production Troubleshooting",
    "category": "Linux",
    "url": "docs.html#linux-troubleshooting",
    "tags": [
      "faang-insight",
      "Linux",
      "troubleshooting",
      "incident response",
      "debugging",
      "SRE"
    ],
    "description": "Production troubleshooting is the art of diagnosing and resolving issues in live systems under pressure. At Enterprise, the expectation is that you…",
    "sections": [
      "Incident Response: The First 5 Minutes",
      "Diagnosing High CPU & Memory Issues",
      "Diagnosing Disk & I/O Issues",
      "Diagnosing Network Issues",
      "Interview Q&A",
      "References & Further Reading"
    ],
    "difficulty": "advanced",
    "readingTime": 17,
    "prerequisites": [
      "linux-processes",
      "linux-networking",
      "linux-storage",
      "linux-systemd"
    ]
  },
  {
    "title": "Linux Networking",
    "category": "Linux",
    "url": "docs.html#linux-networking",
    "tags": [
      "faang-insight",
      "Linux",
      "networking",
      "tcpdump",
      "DNS",
      "iptables",
      "troubleshooting"
    ],
    "description": "Linux networking is a vast topic that every infrastructure engineer must understand. From interface configuration to packet filtering, DNS resolution…",
    "sections": [
      "Network Interfaces & Configuration",
      "Socket Diagnostics: ss, netstat & lsof",
      "DNS Resolution on Linux",
      "Packet Filtering: iptables & nftables",
      "Packet Capture: tcpdump & wireshark",
      "Interview Q&A",
      "References & Further Reading"
    ],
    "difficulty": "intermediate",
    "readingTime": 20,
    "prerequisites": [
      "linux-cli-basics",
      "linux-processes"
    ]
  },
  {
    "title": "Package Management",
    "category": "Linux",
    "url": "docs.html#linux-package-mgmt",
    "tags": [
      "faang-insight",
      "Linux",
      "apt",
      "yum",
      "dnf",
      "package management",
      "containers"
    ],
    "description": "Package management is how Linux systems install, update, and remove software. At Enterprise, you'll work across Debian-based (Ubuntu), RHEL-based…",
    "sections": [
      "Debian/Ubuntu: APT & dpkg",
      "RHEL/CentOS/Amazon Linux: RPM & YUM/DNF",
      "Compiling from Source & Alternatives",
      "Docker & Containers: The Modern \"Package\"",
      "Interview Q&A",
      "References & Further Reading"
    ],
    "difficulty": "intermediate",
    "readingTime": 15,
    "prerequisites": [
      "linux-cli-basics",
      "linux-filesystem"
    ]
  },
  {
    "title": "Process Management & Signals",
    "category": "Linux",
    "url": "docs.html#linux-processes",
    "tags": [
      "faang-insight",
      "Linux",
      "processes",
      "signals",
      "cgroups",
      "production debugging"
    ],
    "description": "Processes are the fundamental unit of execution on Linux. Every program, daemon, and shell command runs as one or more processes. At Enterprise,…",
    "sections": [
      "Process Lifecycle & States",
      "Signals: The Linux Interrupt System",
      "Daemons & Process Supervision",
      "cgroups & Containers (Modern Process Isolation)",
      "Interview Q&A",
      "References & Further Reading"
    ],
    "difficulty": "intermediate",
    "readingTime": 18,
    "prerequisites": [
      "linux-cli-basics",
      "linux-shell-basics"
    ]
  },
  {
    "title": "SSH: Secure Shell",
    "category": "Linux",
    "url": "docs.html#linux-ssh",
    "tags": [
      "faang-insight",
      "Linux",
      "SSH",
      "security",
      "tunneling",
      "authentication"
    ],
    "description": "SSH (Secure Shell) is the universal protocol for remote access to Linux systems. Despite the rise of 'no-SSH' architectures (immutable…",
    "sections": [
      "SSH Authentication: Keys, Certificates & Agents",
      "SSH Client Configuration (~/.ssh/config)",
      "SSH Server Hardening",
      "SSH Tunneling & Port Forwarding",
      "SSH Troubleshooting & Debugging",
      "Interview Q&A",
      "References & Further Reading"
    ],
    "difficulty": "intermediate",
    "readingTime": 19,
    "prerequisites": [
      "linux-users",
      "linux-networking"
    ]
  },
  {
    "title": "Storage, Filesystems & Disk Management",
    "category": "Linux",
    "url": "docs.html#linux-storage",
    "tags": [
      "faang-insight",
      "Linux",
      "storage",
      "filesystem",
      "LVM",
      "disk management",
      "monitoring"
    ],
    "description": "Storage on Linux spans a hierarchy: physical disks → partitions → LVM (logical volumes) → filesystems → mount points. At Enterprise, storage is…",
    "sections": [
      "Disk Discovery & Partitioning",
      "Filesystems: ext4, XFS & Modern Options",
      "Mounting & /etc/fstab",
      "LVM: Logical Volume Manager",
      "Monitoring: I/O, Space & Inodes",
      "Interview Q&A",
      "References & Further Reading"
    ],
    "difficulty": "beginner",
    "readingTime": 20,
    "prerequisites": [
      "linux-filesystem",
      "linux-permissions"
    ]
  },
  {
    "title": "systemd: The Modern Init System",
    "category": "Linux",
    "url": "docs.html#linux-systemd",
    "tags": [
      "faang-insight",
      "Linux",
      "systemd",
      "journald",
      "init",
      "service management"
    ],
    "description": "systemd is the init system and service manager for virtually every modern Linux distribution. It replaced SysV init and handles service startup,…",
    "sections": [
      "Core Concepts: Units & Targets",
      "Writing a Service Unit File",
      "journalctl: The systemd Logging System",
      "Timers (Replacing Cron) & Socket Activation",
      "System Analysis & Debugging",
      "Interview Q&A",
      "References & Further Reading"
    ],
    "difficulty": "intermediate",
    "readingTime": 17,
    "prerequisites": [
      "linux-processes",
      "linux-shell-basics"
    ]
  },
  {
    "title": "Users, Groups & Authentication",
    "category": "Linux",
    "url": "docs.html#linux-users",
    "tags": [
      "faang-insight",
      "Linux",
      "users",
      "groups",
      "sudo",
      "PAM",
      "authentication",
      "security"
    ],
    "description": "Linux is a multi-user operating system from the ground up. Every process runs as a specific user, every file has an owner and group, and access…",
    "sections": [
      "User & Group Fundamentals",
      "sudo: Delegated Privilege",
      "PAM: Pluggable Authentication Modules",
      "Service Accounts & Least Privilege",
      "Interview Q&A",
      "References & Further Reading"
    ],
    "difficulty": "advanced",
    "readingTime": 14,
    "prerequisites": [
      "linux-permissions",
      "linux-filesystem"
    ]
  }
];
