// Dynamic Content Loader for ai bytes Documentation Portal
// Route map generated by scripts/build.mjs — uses window.__ROUTE_MAP

let scrollSpyCleanup = null;

const _routeMap = window.__ROUTE_MAP || {};

// ponytail: hash-based tag colors — no palette maintenance needed
var _TAG_COLORS = ['#4585e8','#34d399','#fbbf24','#c4b5fd','#fb923c','#6366f1','#0ea5e9','#ef4444','#a855f7','#10b981','#f59e0b','#ec4899','#f97316','#d946ef','#22c55e','#eab308','#7c3aed','#2dd4bf'];
function colorizeTags(root) {
  (root || document).querySelectorAll('[data-tag]').forEach(function(el) {
    var t = el.getAttribute('data-tag');
    var h = 0; for (var i = 0; i < t.length; i++) h = ((h << 5) - h) + t.charCodeAt(i);
    var c = _TAG_COLORS[Math.abs(h) % _TAG_COLORS.length];
    el.style.setProperty('--tag-color', c);
    el.style.setProperty('--tag-bg', c + '1A');
    if (document.documentElement.classList.contains('dark')) {
      el.style.setProperty('--tag-bg', c + '2E');
    }
  });
}


// localStorage Helpers for Study Progress and Bookmarks
function getBookmarks() {
  try { return JSON.parse(localStorage.getItem('ab_bookmarks')) || []; } catch (e) { return []; }
}
function saveBookmarks(bookmarks) {
  localStorage.setItem('ab_bookmarks', JSON.stringify(bookmarks));
}
function getProgress() {
  try { return JSON.parse(localStorage.getItem('ab_progress')) || []; } catch (e) { return []; }
}
function saveProgress(progress) {
  localStorage.setItem('ab_progress', JSON.stringify(progress));
}

function toggleBookmark(hash) {
  var bookmarks = getBookmarks();
  var index = bookmarks.indexOf(hash);
  if (index > -1) {
    bookmarks.splice(index, 1);
  } else {
    bookmarks.push(hash);
  }
  saveBookmarks(bookmarks);
  updateBookmarkUI(hash);
  updateSidebarBookmarks();
  updateSidebarLinksUI();
}
window.toggleBookmark = toggleBookmark;

function toggleProgress(hash) {
  var progress = getProgress();
  var index = progress.indexOf(hash);
  if (index > -1) {
    progress.splice(index, 1);
  } else {
    progress.push(hash);
  }
  saveProgress(progress);
  updateProgressUI(hash);
  updateSidebarProgress();
  updateSidebarLinksUI();
}
window.toggleProgress = toggleProgress;

function updateBookmarkUI(hash) {
  if (window.location.hash !== hash && (window.location.hash || '#linux-history') !== hash) return;
  var btn = document.getElementById('btn-bookmark');
  if (!btn) return;
  var isBookmarked = getBookmarks().includes(hash);
  var icon = btn.querySelector('.material-symbols-outlined');
  if (icon) {
    icon.textContent = isBookmarked ? 'star' : 'star_border';
    if (isBookmarked) {
      btn.classList.add('text-amber-500', 'border-amber-500/40', 'bg-amber-500/5');
      btn.classList.remove('text-slate-400');
    } else {
      btn.classList.remove('text-amber-500', 'border-amber-500/40', 'bg-amber-500/5');
      btn.classList.add('text-slate-400');
    }
  }
}

function updateProgressUI(hash) {
  if (window.location.hash !== hash && (window.location.hash || '#linux-history') !== hash) return;
  var btn = document.getElementById('btn-progress');
  if (!btn) return;
  var isCompleted = getProgress().includes(hash);
  var icon = btn.querySelector('.material-symbols-outlined');
  var text = btn.querySelector('.progress-btn-text');
  if (icon && text) {
    icon.textContent = isCompleted ? 'check_circle' : 'circle';
    text.textContent = isCompleted ? 'Completed' : 'Mark as Done';
    if (isCompleted) {
      icon.classList.add('text-emerald-500');
      icon.classList.remove('text-slate-400');
      btn.classList.add('text-emerald-600', 'border-emerald-500/40', 'bg-emerald-500/5');
    } else {
      icon.classList.remove('text-emerald-500');
      icon.classList.add('text-slate-400');
      btn.classList.remove('text-emerald-600', 'border-emerald-500/40', 'bg-emerald-500/5');
    }
  }
}

function updateSidebarProgress() {
  var progress = getProgress();
  var total = Object.keys(_routeMap).length;
  var completedCount = progress.filter(function(hash) { return _routeMap[hash]; }).length;
  var percentage = total > 0 ? Math.round((completedCount / total) * 100) : 0;
  
  var textEl = document.getElementById('sidebar-progress-text');
  var barEl = document.getElementById('sidebar-progress-bar');
  var statsEl = document.getElementById('sidebar-progress-stats');
  
  if (textEl) textEl.textContent = percentage + '%';
  if (barEl) barEl.style.width = percentage + '%';
  if (statsEl) statsEl.textContent = completedCount + ' of ' + total + ' topics completed';
}

function updateSidebarBookmarks() {
  var bookmarks = getBookmarks();
  var container = document.getElementById('sidebar-bookmarks-container');
  var list = document.getElementById('sidebar-bookmarks-list');
  if (!container || !list) return;
  
  var validBookmarks = bookmarks.filter(function(hash) { return _routeMap[hash]; });
  
  if (validBookmarks.length === 0) {
    container.classList.add('hidden');
    return;
  }
  
  container.classList.remove('hidden');
  list.innerHTML = validBookmarks.map(function(hash) {
    var title = hash;
    var entry = (window.__SEARCH_INDEX || []).find(function(e) { return e.url === 'docs.html' + hash; });
    if (entry) {
      title = entry.title;
      if (title.length > 24) title = title.substring(0, 22) + '...';
    }
    return '<a href="' + hash + '" class="sidebar-link !py-1 flex items-center justify-between hover:text-brand-500">' +
      '<span class="truncate">' + title + '</span>' +
      '<span class="material-symbols-outlined text-[12px] text-amber-500">star</span>' +
      '</a>';
  }).join('');
}

function updateSidebarLinksUI() {
  var progress = getProgress();
  document.querySelectorAll('.sidebar-link').forEach(function(link) {
    var href = link.getAttribute('href');
    if (!href || !href.startsWith('#')) return;
    
    var isCompleted = progress.includes(href);
    var checkIndicator = link.querySelector('.completion-indicator');
    if (isCompleted) {
      if (!checkIndicator) {
        checkIndicator = document.createElement('span');
        checkIndicator.className = 'completion-indicator material-symbols-outlined text-[13px] text-emerald-500 ml-auto shrink-0';
        checkIndicator.textContent = 'check_circle';
        link.appendChild(checkIndicator);
      } else {
        checkIndicator.classList.remove('hidden');
      }
    } else {
      if (checkIndicator) {
        checkIndicator.classList.add('hidden');
      }
    }
  });
}

function getContentMeta(data) {
  var readingTime = data.readingTime || (function() {
    var text = data.description || '';
    if (data.sections) {
      data.sections.forEach(function(s) {
        if (s.title) text += ' ' + s.title;
        if (s.description) text += ' ' + s.description;
        if (s.codeBlock) text += ' ' + s.codeBlock;
      });
    }
    var cleanText = text.replace(/<[^>]*>/g, ' ');
    var words = cleanText.split(/\s+/).filter(function(w) { return w.length > 0; }).length;
    var codeBlocks = 0;
    if (data.sections) data.sections.forEach(function(s) { if (s.codeBlock) codeBlocks++; });
    if (data.codeBlock) codeBlocks++;
    return Math.max(5, Math.round((words / 200) + (codeBlocks * 0.25)));
  })();
  
  var diffConfig = {
    beginner: { label: 'Beginner', color: 'difficulty-beginner', icon: 'signal_cellular_1_bar' },
    intermediate: { label: 'Intermediate', color: 'difficulty-intermediate', icon: 'signal_cellular_3_bar' },
    advanced: { label: 'Advanced', color: 'difficulty-advanced', icon: 'signal_cellular_4_bar' }
  };
  var diffKey = data.difficulty || 'beginner';
  if (!diffConfig[diffKey]) diffKey = 'beginner';
  
  return {
    time: readingTime,
    practiceTime: data.practiceTime || Math.round(readingTime * 0.75),
    difficulty: diffConfig[diffKey].label,
    diffColor: diffConfig[diffKey].color,
    diffIcon: diffConfig[diffKey].icon,
    rawDifficulty: diffKey
  };
}

function getRelatedTopics(currentHash, currentTags, currentCategory) {
  if (!currentTags || currentTags.length === 0) return [];
  var searchIndex = window.__SEARCH_INDEX || [];
  var currentUrl = 'docs.html' + currentHash;
  
  var related = [];
  searchIndex.forEach(function(item) {
    if (item.url === currentUrl) return;
    
    var common = 0;
    (item.tags || []).forEach(function(t) {
      if (currentTags.includes(t)) common++;
    });
    
    if (common > 0) {
      related.push({
        item: item,
        score: common + (item.category === currentCategory ? 0.5 : 0)
      });
    }
  });
  
  related.sort(function(a, b) { return b.score - a.score; });
  return related.slice(0, 3).map(function(r) { return r.item; });
}

function renderRelatedTopics(currentHash, currentTags, currentCategory) {
  var related = getRelatedTopics(currentHash, currentTags, currentCategory);
  if (related.length === 0) return '';
  
  var cards = related.map(function(item) {
    var hash = item.url.substring(item.url.indexOf('#'));
    return `
      <a href="${hash}" class="related-topic-card flex flex-col gap-2 p-4 rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-[#0E1115] group cursor-pointer">
        <span class="text-[9px] font-bold text-slate-400 dark:text-slate-500 uppercase tracking-wider">${item.category}</span>
        <h4 class="text-sm font-semibold text-slate-900 dark:text-white group-hover:text-brand-500 transition-colors">${item.title}</h4>
        <p class="text-xs text-slate-500 dark:text-slate-400 line-clamp-2 flex-1">${item.description}</p>
        <span class="text-xs font-semibold text-brand-500 opacity-0 group-hover:opacity-100 transition-opacity flex items-center gap-1 mt-1">
          Read Guide
          <span class="material-symbols-outlined text-[13px]">arrow_forward</span>
        </span>
      </a>
    `;
  }).join('');
  
  return `
    <div class="mt-8 border-t border-slate-200 dark:border-slate-800 pt-6">
      <h3 class="text-xs font-bold text-slate-400 dark:text-slate-500 uppercase tracking-wider mb-4 flex items-center gap-1.5 select-none">
        <span class="material-symbols-outlined text-[16px] text-brand-500">grid_view</span> Related Study Guides
      </h3>
      <div class="grid grid-cols-1 sm:grid-cols-3 gap-4">
        ${cards}
      </div>
    </div>
  `;
}

async function fetchWithCache(path) {
  var cacheKey = 'ab:' + path;
  try {
    var cached = sessionStorage.getItem(cacheKey);
    if (cached) {
      var parsed = JSON.parse(cached);
      if (parsed && typeof parsed === 'object') return parsed;
    }
  } catch (e) {}
  var res = await fetch(path);
  if (!res.ok) throw new Error('Failed to fetch content');
  var data = await res.json();
  try { sessionStorage.setItem(cacheKey, JSON.stringify(data)); } catch (e) {}
  return data;
}

const COPY_BTN = '<button onclick="copyCode(this)" class="absolute right-3 top-3 opacity-0 group-hover:opacity-100 bg-white dark:bg-slate-900 hover:bg-slate-100 dark:hover:bg-slate-800 border border-slate-200 dark:border-slate-800 px-2.5 py-1.5 rounded-lg text-xs font-sans text-slate-500 transition-all flex items-center gap-1.5"><span class="material-symbols-outlined text-sm" aria-hidden="true">content_copy</span> Copy</button>';

function codeBlock(code, langClass) {
  return `<div class="border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-800/40 rounded-xl p-5 text-sm leading-relaxed overflow-x-auto relative group">${COPY_BTN}<pre><code class="${langClass}">${escapeHtml(code)}</code></pre></div>`;
}

function renderSections(sections, dataId, langClass, extraClass) {
  if (!sections) return '';
  return `<div class="flex flex-col gap-8${extraClass || ''}">` + sections.map(function(section, idx) {
    let sectionId = 'section-' + dataId + '-' + idx;
    let refClass = '';
    if (section.title && section.title.indexOf('References') !== -1) {
      refClass = ' references-section';
    }
    let sectionLangClass = section.language ? 'language-' + section.language : langClass;
    let titleHtml = section.title ? '<h3 class="text-xl font-semibold text-slate-900 dark:text-white">' + section.title + '</h3>' : '';
    return (
      '<div id="' + sectionId + '" class="scroll-mt-24 flex flex-col gap-3' + refClass + '">' +
      titleHtml +
      (section.description ? '<div class="text-slate-600 dark:text-slate-400 text-sm leading-relaxed">' + section.description + '</div>' : '') +
      (section.codeBlock ? codeBlock(section.codeBlock, sectionLangClass) : '') +
      '</div>'
    );
  }).join('\n') + '</div>';
}

function getChapterTitle(id) {
  var entry = (window.__SEARCH_INDEX || []).find(function(e) { return e.url === 'docs.html#' + id; });
  return entry ? entry.title : id;
}

function renderDifficultyBadge(diffKey, label) {
  return '<span class="difficulty-badge ' + (diffKey === 'beginner' ? 'difficulty-beginner' : diffKey === 'intermediate' ? 'difficulty-intermediate' : 'difficulty-advanced') + '">' +
    '<span class="material-symbols-outlined" style="font-size:12px">' + (diffKey === 'beginner' ? 'signal_cellular_1_bar' : diffKey === 'intermediate' ? 'signal_cellular_3_bar' : 'signal_cellular_4_bar') + '</span>' +
    '<span>' + label + '</span></span>';
}

function renderPrerequisites(prereqs) {
  if (!prereqs || prereqs.length === 0) return '';
  var chips = prereqs.map(function(id) {
    var title = getChapterTitle(id);
    return '<a href="#' + id + '" class="prereq-chip">' +
      '<span class="material-symbols-outlined" style="font-size:12px">chevron_right</span>' +
      title + '</a>';
  }).join('');
  return '<div class="flex flex-col gap-1.5">' +
    '<div class="icon-heading icon-heading-objectives"><span class="material-symbols-outlined">school</span>Prerequisites</div>' +
    '<div class="prereq-list">' + chips + '</div></div>';
}

function renderLearningObjectives(objectives) {
  if (!objectives || objectives.length === 0) return '';
  var items = objectives.map(function(obj) {
    return '<li class="objective-item"><span class="material-symbols-outlined">checklist</span><span>' + obj + '</span></li>';
  }).join('');
  return '<div class="flex flex-col gap-2 lcm-section" id="section-objectives">' +
    '<div class="icon-heading icon-heading-objectives"><span class="material-symbols-outlined">track_changes</span>Learning Objectives</div>' +
    '<ul class="objectives-list">' + items + '</ul></div>';
}

function renderAnalogy(analogy) {
  if (!analogy || !analogy.title) return '';
  return '<div class="analogy-box lcm-section" id="section-analogy">' +
    '<div class="flex items-center gap-2 mb-1">' +
    '<span class="material-symbols-outlined" style="font-size:16px;color:#f59e0b">lightbulb</span>' +
    '<div class="analogy-title">' + analogy.title + '</div></div>' +
    '<div class="analogy-body">' + analogy.description + '</div></div>';
}

function renderCommonMistakes(mistakes) {
  if (!mistakes || mistakes.length === 0) return '';
  var items = mistakes.map(function(m) {
    return '<div class="mistake-item">' +
      '<div class="mistake-text"><span class="material-symbols-outlined" style="font-size:14px;vertical-align:middle;margin-right:4px">warning</span>' + m.mistake + '</div>' +
      '<div class="mistake-solution">' + m.solution + '</div></div>';
  }).join('');
  return '<div class="flex flex-col gap-1 lcm-section" id="section-mistakes">' +
    '<div class="icon-heading icon-heading-mistakes"><span class="material-symbols-outlined">error_outline</span>Common Mistakes</div>' +
    '<div class="mistakes-box">' + items + '</div></div>';
}

function renderPracticeLabs(labs) {
  if (!labs || labs.length === 0) return '';
  var items = labs.map(function(lab) {
    return '<div class="lab-box">' +
      '<div class="lab-title"><span class="material-symbols-outlined" style="font-size:14px;vertical-align:middle;margin-right:4px">terminal</span>' + lab.title + '</div>' +
      (lab.task ? '<div class="lab-task">' + lab.task + '</div>' : '') +
      (lab.expectedOutput ? '<div class="lab-expected">Expected: ' + lab.expectedOutput + '</div>' : '') +
      (lab.hint ? '<div class="lab-hint">Hint: ' + lab.hint + '</div>' : '') +
      '</div>';
  }).join('');
  return '<div class="flex flex-col gap-2 lcm-section" id="section-labs">' +
    '<div class="icon-heading icon-heading-lab"><span class="material-symbols-outlined">build</span>Practice Labs</div>' +
    items + '</div>';
}

function renderQuickReference(qr) {
  if (!qr || !qr.content) return '';
  // Parse markdown table and render as HTML
  var content = qr.content;
  var title = qr.title || 'Quick Reference';
  
  // If content looks like a markdown table, parse it
  var html = content;
  if (content.includes('|')) {
    var lines = content.split('\n').filter(function(l) { return l.trim(); });
    if (lines.length >= 2) {
      var tableHtml = '<table class="quickref-table">';
      var headerRow = lines[0];
      var headers = headerRow.split('|').filter(function(c) { return c.trim(); });
      tableHtml += '<thead><tr>' + headers.map(function(h) { return '<th>' + h.trim() + '</th>'; }).join('') + '</tr></thead>';
      tableHtml += '<tbody>';
      for (var i = 2; i < lines.length; i++) {
        var cells = lines[i].split('|').filter(function(c) { return c.trim(); });
        if (cells.length > 0) {
          tableHtml += '<tr>' + cells.map(function(c) { return '<td>' + c.trim() + '</td>'; }).join('') + '</tr>';
        }
      }
      tableHtml += '</tbody></table>';
      html = tableHtml;
    }
  }
  
  return '<div class="flex flex-col gap-2 lcm-section" id="section-reference">' +
    '<div class="icon-heading icon-heading-reference"><span class="material-symbols-outlined">summarize</span>' + title + '</div>' +
    html + '</div>';
}

function renderTroubleshooting(ts) {
  if (!ts || ts.length === 0) return '';
  var items = ts.map(function(t) {
    return '<div class="ts-item">' +
      '<div class="ts-symptom"><span class="material-symbols-outlined" style="font-size:14px;vertical-align:middle;margin-right:4px">bug_report</span>' + t.symptom + '</div>' +
      (t.cause ? '<div class="ts-cause">Cause: ' + t.cause + '</div>' : '') +
      (t.solution ? '<div class="ts-solution">Solution: ' + t.solution + '</div>' : '') +
      '</div>';
  }).join('');
  return '<div class="flex flex-col gap-1 lcm-section" id="section-troubleshooting">' +
    '<div class="icon-heading icon-heading-troubleshooting"><span class="material-symbols-outlined">health_and_safety</span>Troubleshooting</div>' +
    '<div class="troubleshooting-box">' + items + '</div></div>';
}

function renderQuiz(quiz) {
  if (!quiz || quiz.length === 0) return '';
  var items = quiz.map(function(q, idx) {
    var optionsHtml = '';
    if (q.options && q.options.length > 0) {
      optionsHtml = '<div class="quiz-options">' + q.options.map(function(opt, oi) {
        return '<div class="quiz-option" onclick="this.parentElement.nextElementSibling.classList.toggle(\'revealed\')">' +
          '<span class="radio-circle"></span><span>' + opt + '</span></div>';
      }).join('') + '</div>';
    }
    return '<div class="quiz-item">' +
      '<div class="quiz-question">' + (idx + 1) + '. ' + q.question + '</div>' +
      optionsHtml +
      '<div class="quiz-answer" id="quiz-answer-' + idx + '">' +
      '<div class="answer-label">Answer:</div> ' + q.answer +
      (q.explanation ? '<div style="margin-top:4px;color:#94a3b8;font-size:11px;">' + q.explanation + '</div>' : '') +
      '</div>' +
      '<button class="quiz-show-btn" onclick="document.getElementById(\'quiz-answer-' + idx + '\').classList.toggle(\'revealed\');this.textContent=this.textContent===\'Show Answer\'?\'Hide Answer\':\'Show Answer\'">Show Answer</button>' +
      '</div>';
  }).join('');
  return '<div class="flex flex-col gap-2 lcm-section" id="section-quiz">' +
    '<div class="icon-heading icon-heading-quiz"><span class="material-symbols-outlined">quiz</span>Quick Quiz</div>' +
    '<div class="quiz-section">' + items + '</div></div>';
}

function renderInterviewTips(tips) {
  if (!tips || tips.length === 0) return '';
  var items = tips.map(function(t) { return '<li>' + t + '</li>'; }).join('');
  return '<div class="flex flex-col gap-1 lcm-section" id="section-interview">' +
    '<div class="icon-heading icon-heading-interview"><span class="material-symbols-outlined">record_voice_over</span>Interview Tips</div>' +
    '<div class="interview-box"><ul>' + items + '</ul></div></div>';
}

function renderProductionTips(tips) {
  if (!tips || tips.length === 0) return '';
  var items = tips.map(function(t) { return '<li>' + t + '</li>'; }).join('');
  return '<div class="flex flex-col gap-1 lcm-section" id="section-production">' +
    '<div class="icon-heading icon-heading-production"><span class="material-symbols-outlined">settings</span>Production Tips</div>' +
    '<div class="production-box"><ul>' + items + '</ul></div></div>';
}

function renderBestPractices(practices) {
  if (!practices || practices.length === 0) return '';
  var items = practices.map(function(p) {
    return '<div class="practice-item"><span class="material-symbols-outlined">check_circle</span><span>' + p + '</span></div>';
  }).join('');
  return '<div class="flex flex-col gap-1 lcm-section" id="section-practices">' +
    '<div class="icon-heading icon-heading-practice"><span class="material-symbols-outlined">star</span>Best Practices</div>' +
    '<div class="practice-box">' + items + '</div></div>';
}

function renderEnterprisePerspective(perspective) {
  if (!perspective) return '';
  return '<div class="flex flex-col gap-1 lcm-section" id="section-enterprise">' +
    '<div class="icon-heading icon-heading-enterprise"><span class="material-symbols-outlined">business</span>Enterprise Perspective</div>' +
    '<div class="enterprise-box">' + perspective + '</div></div>';
}

async function loadContent(hash) {
  if (scrollSpyCleanup) {
    scrollSpyCleanup();
    scrollSpyCleanup = null;
  }
  const path = _routeMap[hash] || _routeMap['#linux-history'];
  const contentArea = document.getElementById('docs-dynamic-content');
  if (!contentArea) return;

  // Show loading state
  contentArea.innerHTML = `
    <div class="animate-pulse space-y-6">
      <div class="h-8 bg-slate-200 dark:bg-slate-800 rounded w-3/4"></div>
      <div class="h-4 bg-slate-200 dark:bg-slate-800 rounded w-1/2"></div>
      <div class="h-40 bg-slate-200 dark:bg-slate-800 rounded"></div>
      <div class="h-4 bg-slate-200 dark:bg-slate-800 rounded w-5/6"></div>
    </div>
  `;

  if (hash === '#readme') {
    try {
      const res = await fetch('README.md');
      const md = await res.text();

      const existing = document.getElementById('readme-modal');
      if (existing) existing.remove();

      const modal = document.createElement('div');
      modal.id = 'readme-modal';
      modal.className = 'fixed inset-0 z-50 flex items-start justify-center pt-12 sm:pt-20 px-4';
      modal.innerHTML =
        '<div class="fixed inset-0 bg-black/30 dark:bg-black/50 backdrop-blur-sm" id="readme-modal-backdrop"></div>' +
        '<div class="relative z-10 w-full max-w-3xl max-h-[80vh] bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl shadow-2xl overflow-hidden flex flex-col">' +
          '<div class="flex items-center justify-between px-6 py-4 border-b border-slate-200 dark:border-slate-800 shrink-0">' +
            '<h2 class="text-sm font-bold text-slate-900 dark:text-white font-sans">README — ai bytes</h2>' +
            '<button id="readme-modal-close" class="w-7 h-7 rounded-lg hover:bg-slate-100 dark:hover:bg-white/5 flex items-center justify-center text-slate-400 hover:text-slate-600 dark:hover:text-slate-300 transition-all" aria-label="Close README">' +
              '<span class="material-symbols-outlined text-[18px]">close</span>' +
            '</button>' +
          '</div>' +
          '<div class="flex-1 overflow-y-auto px-6 py-5 readme-content min-h-0">' + marked.parse(md) + '</div>' +
        '</div>';

      document.body.appendChild(modal);

      if (typeof Prism !== 'undefined') {
        Prism.highlightAllUnder(modal);
      }

      function closeReadme() {
        modal.remove();
        window.location.hash = '#linux-history';
      }

      document.getElementById('readme-modal-close').addEventListener('click', closeReadme);
      document.getElementById('readme-modal-backdrop').addEventListener('click', closeReadme);
      document.addEventListener('keydown', function handler(e) {
        if (e.key === 'Escape' && document.getElementById('readme-modal')) {
          closeReadme();
          document.removeEventListener('keydown', handler);
        }
      });
    } catch (e) {
      contentArea.innerHTML = '<p class="text-red-500 dark:text-red-400">Failed to load README.md</p>';
    }
    return;
  }

  const left = document.getElementById('left-sidebar');
  const outline = document.getElementById('docs-right-outline');
  if (left) left.style.display = '';
  if (outline) outline.parentElement.style.display = '';
  const mainEl = document.querySelector('main');
  if (mainEl) {
    mainEl.classList.remove('max-w-4xl');
    mainEl.classList.add('max-w-3xl');
  }

  try {
    const data = await fetchWithCache(path);

    // Render content dynamically
    const langClass = data.language ? 'language-' + data.language : 'text-slate-800 dark:text-slate-200';
    let embedCode = '';
    const isInteractive = data.interactive === true;
    if (isInteractive) {
      embedCode = `
        <div class="w-full aspect-auto h-[530px] md:aspect-[16/12] md:h-auto border border-blue-200 dark:border-gray-700 rounded-2xl overflow-hidden shadow-lg bg-white dark:bg-[#0F1115]">
          <iframe src="${data.id}.html" class="w-full h-full border-none" allowfullscreen aria-label="${data.title || 'Interactive visualization'}"></iframe>
        </div>
      `;
      if (data.sections) {
        embedCode += renderSections(data.sections, data.id, langClass, ' mt-8');
      } else if (data.codeBlock) {
        embedCode += `
          <div class="mt-6 text-xs font-mono font-bold uppercase tracking-wider text-slate-400 dark:text-slate-500 mb-2">Sample Code / Syntax</div>
          <div id="section-syntax" class="scroll-mt-24">${codeBlock(data.codeBlock, langClass)}</div>
        `;
      }
    } else if (data.sections) {
      embedCode = renderSections(data.sections, data.id, langClass, '');
    } else if (data.timeline) {
      let items = '';
      for (let ti = 0; ti < data.timeline.length; ti++) {
        const t = data.timeline[ti];
        const delay = ti * 80;
        items += `
          <div class="timeline-entry" style="animation-delay: ${delay}ms">
            <div class="timeline-dot">
              <span class="timeline-dot-year">${t.year}</span>
              <span class="timeline-dot-ring"></span>
            </div>
            <div class="timeline-body">
              <div class="flex items-center gap-2 mb-1">
                <h4 class="timeline-title">${t.title || ''}</h4>
                <span class="timeline-tag">${t.tag || 'Release'}</span>
              </div>
              <p class="timeline-event">${t.event}</p>
            </div>
          </div>
        `;
      }
      embedCode = `
        <div id="section-syntax" class="scroll-mt-24 mt-4">
          <div class="timeline-track">${items}</div>
        </div>
      `;
      if (data.codeBlock) {
        embedCode += `<div class="mt-6">${codeBlock(data.codeBlock, langClass)}</div>`;
      }
    } else {
      embedCode = `<div id="section-syntax" class="scroll-mt-24">${data.codeBlock ? codeBlock(data.codeBlock, langClass) : ''}</div>`;
    }

    var meta = getContentMeta(data);
    var relatedHtml = renderRelatedTopics(hash, data.tags, data.category);

    contentArea.innerHTML = `
      <article class="flex flex-col gap-6 docs-section" role="region" aria-label="${data.title || 'Documentation content'}">
        <div class="flex flex-col gap-3">
          <div class="flex items-center justify-between gap-4 flex-wrap select-none">
            <nav class="flex items-center gap-1.5 text-[10px] font-bold text-slate-400 dark:text-slate-500 uppercase tracking-wider">
              <span>${data.category}</span>
              <span class="material-symbols-outlined text-[12px] text-slate-300 dark:text-slate-700">chevron_right</span>
              <span class="text-brand-500">${data.subcategory}</span>
            </nav>
            
            <!-- Article Action Buttons -->
            <div class="flex items-center gap-2" id="article-actions-toolbar">
              <button onclick="toggleBookmark('${hash}')" id="btn-bookmark" class="w-8 h-8 rounded-lg border border-slate-200 dark:border-slate-800 text-slate-400 hover:text-amber-500 hover:border-amber-500/30 flex items-center justify-center transition-all bg-white dark:bg-slate-900" aria-label="Pin this guide">
                <span class="material-symbols-outlined text-[18px]">star_border</span>
              </button>
              
              <button onclick="toggleProgress('${hash}')" id="btn-progress" class="h-8 px-3 rounded-lg border border-slate-200 dark:border-slate-800 text-slate-500 hover:text-emerald-500 hover:border-emerald-500/30 flex items-center gap-1.5 text-[11px] font-semibold transition-all bg-white dark:bg-slate-900">
                <span class="material-symbols-outlined text-[16px] text-slate-400">circle</span>
                <span class="progress-btn-text">Mark as Done</span>
              </button>
            </div>
          </div>
          
          <!-- Document Title -->
          <h1 class="text-3xl sm:text-4xl font-bold text-slate-900 dark:text-white tracking-tight">${data.title}</h1>
          
          <!-- Metadata Badges (LCM) -->
          <div class="metadata-row">
            ${renderDifficultyBadge(meta.rawDifficulty, meta.difficulty)}
            <span class="meta-item">
              <span class="material-symbols-outlined">schedule</span>
              <span>${meta.time} min read</span>
            </span>
            <span class="meta-item">
              <span class="material-symbols-outlined">terminal</span>
              <span>${meta.practiceTime} min practice</span>
            </span>
          </div>

          <!-- Tags List -->
          ${data.tags && data.tags.length > 0 ? `
            <div class="flex flex-wrap gap-1.5 mt-0.5">
              ${data.tags.map(function(t) {
                return '<span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-[10px] font-semibold uppercase tracking-wider tag-badge cursor-default" data-tag="' + t + '">' + t + '</span>';
              }).join('')}
            </div>
          ` : ''}
        </div>

        <!-- LCM Sections -->
        
        <!-- Prerequisites -->
        ${renderPrerequisites(data.prerequisites)}
        
        <!-- Learning Objectives -->
        ${renderLearningObjectives(data.learningObjectives)}
        
        <!-- Why This Matters -->
        <div class="flex flex-col gap-1 lcm-section" id="section-why">
          <div class="icon-heading icon-heading-why"><span class="material-symbols-outlined">info</span>Why This Matters</div>
          <div class="why-box">${data.description}</div>
        </div>
        
        <!-- Analogy -->
        ${renderAnalogy(data.analogy)}
        
        <!-- Content Sections -->
        ${embedCode}
        
        ${data.comparisonTable ? `
          <div id="section-comparison" class="scroll-mt-24">
            <h4 class="text-xs font-mono font-bold uppercase tracking-wider text-orange-600 dark:text-orange-400 mb-3 mt-6">${data.comparisonTableTitle || 'Comparison Matrix'}</h4>
            <div class="overflow-x-auto border border-slate-200 dark:border-slate-800 rounded-xl bg-white dark:bg-[#0E1115]">
              <table class="w-full text-xs text-left border-collapse">
                <thead class="bg-slate-50 dark:bg-slate-900/60 font-bold font-mono border-b border-slate-200 dark:border-slate-800">
                  <tr>
                    <th class="p-3 text-slate-700 dark:text-slate-200">Model</th>
                    <th class="p-3 text-slate-700 dark:text-slate-200">Execution Paradigm</th>
                    <th class="p-3 text-slate-700 dark:text-slate-200">GIL Restriction</th>
                    <th class="p-3 text-slate-700 dark:text-slate-200">Memory Overhead</th>
                    <th class="p-3 text-slate-700 dark:text-slate-200">Best Suitability</th>
                  </tr>
                </thead>
                <tbody class="font-mono divide-y divide-slate-100 dark:divide-slate-800/60">
                  ${data.comparisonTable.map(row => `
                    <tr class="hover:bg-slate-50/50 dark:hover:bg-slate-900/20">
                      <td class="p-3 font-semibold ${row.colorClass || 'text-slate-800 dark:text-slate-200'}">${row.model}</td>
                      <td class="p-3">${row.paradigm}</td>
                      <td class="p-3 ${row.gilColorClass || ''}">${row.gil}</td>
                      <td class="p-3">${row.memory}</td>
                      <td class="p-3">${row.suitability}</td>
                    </tr>
                  `).join('')}
                </tbody>
              </table>
            </div>
          </div>
        ` : ''}

        ${data.diffTable ? `
          <div id="section-differences" class="scroll-mt-24">
            <h4 class="text-xs font-mono font-bold uppercase tracking-wider text-orange-600 dark:text-orange-400 mb-3 mt-6">Differences: Multithreading vs Concurrency</h4>
            <div class="overflow-x-auto border border-slate-200 dark:border-slate-800 rounded-xl bg-white dark:bg-[#0E1115]">
              <table class="w-full text-xs text-left border-collapse table-fixed">
                <thead class="bg-slate-50 dark:bg-slate-900/60 font-bold font-mono border-b border-slate-200 dark:border-slate-800">
                  <tr>
                    <th class="p-3 text-slate-700 dark:text-slate-200 w-[20%] align-top">Dimension</th>
                    <th class="p-3 text-slate-700 dark:text-slate-200 w-[40%] align-top">Concurrency</th>
                    <th class="p-3 text-slate-700 dark:text-slate-200 w-[40%] align-top">Multithreading</th>
                  </tr>
                </thead>
                <tbody class="divide-y divide-slate-100 dark:divide-slate-800/60">
                  ${data.diffTable.map(row => `
                    <tr class="hover:bg-slate-50/50 dark:hover:bg-slate-900/20">
                      <td class="p-3 font-mono font-semibold text-orange-600 dark:text-orange-400 align-top">${row.dimension}</td>
                      <td class="p-3 text-slate-600 dark:text-slate-300 text-xs align-top leading-relaxed">${row.concurrency}</td>
                      <td class="p-3 text-slate-600 dark:text-slate-300 text-xs align-top leading-relaxed">${row.multithreading}</td>
                    </tr>
                  `).join('')}
                </tbody>
              </table>
            </div>
          </div>
        ` : ''}

        <!-- Common Mistakes -->
        ${renderCommonMistakes(data.commonMistakes)}
        
        <!-- Practice Labs -->
        ${renderPracticeLabs(data.practiceLabs)}
        
        <!-- Quick Reference -->
        ${renderQuickReference(data.quickReference)}
        
        <!-- Troubleshooting -->
        ${renderTroubleshooting(data.troubleshooting)}
        
        <!-- Quiz -->
        ${renderQuiz(data.quiz)}
        
        <!-- Interview Tips -->
        ${renderInterviewTips(data.interviewTips)}
        
        <!-- Production Tips -->
        ${renderProductionTips(data.productionTips)}
        
        <!-- Best Practices -->
        ${renderBestPractices(data.bestPractices)}
        
        <!-- Enterprise Perspective -->
        ${renderEnterprisePerspective(data.enterprisePerspective)}
        
        ${relatedHtml}
      </article>
    `;

    updateBookmarkUI(hash);
    updateProgressUI(hash);
    updateSidebarProgress();
    updateSidebarBookmarks();
    updateSidebarLinksUI();
    addCopyButtonsToPreElements(contentArea);

    colorizeTags(contentArea);

    // Highlight active link and its parent section in left sidebar
    document.querySelectorAll('.sidebar-section').forEach(function(section) {
      section.classList.remove('section-active');
    });
    document.querySelectorAll('.sidebar-link').forEach(link => {
      if (link.getAttribute('href') === hash) {
        link.classList.add('active-doc-link');
        link.setAttribute('aria-current', 'page');
        var section = link.closest('.sidebar-section');
        if (section) section.classList.add('section-active');
      } else {
        link.classList.remove('active-doc-link');
        link.removeAttribute('aria-current');
      }
    });

    // Populate right outline dynamically
    const outlineArea = document.getElementById('docs-right-outline');
    if (outlineArea) {
      var outlineLinks = [];
      
      // Add LCM section outline entries if data has them
      if (data.prerequisites && data.prerequisites.length > 0) outlineLinks.push({ href: '#section-objectives', label: 'Prerequisites' });
      if (data.learningObjectives && data.learningObjectives.length > 0) outlineLinks.push({ href: '#section-objectives', label: 'Learning Objectives' });
      if (data.analogy && data.analogy.title) outlineLinks.push({ href: '#section-analogy', label: 'Analogy' });
      
      if (data.sections) {
        data.sections.forEach((section, idx) => {
          if (!section.title) return;
          const sectionId = 'section-' + data.id + '-' + idx;
          outlineLinks.push({ href: '#' + sectionId, label: section.title });
        });
      } else if (data.timeline) {
        outlineLinks.push({ href: '#section-syntax', label: 'Timeline' });
      } else {
        outlineLinks.push({ href: '#section-syntax', label: 'Syntax Guide' });
      }
      
      if (data.comparisonTable) outlineLinks.push({ href: '#section-comparison', label: 'Comparison Matrix' });
      if (data.diffTable) outlineLinks.push({ href: '#section-differences', label: 'Differences Matrix' });
      if (data.commonMistakes && data.commonMistakes.length > 0) outlineLinks.push({ href: '#section-mistakes', label: 'Common Mistakes' });
      if (data.practiceLabs && data.practiceLabs.length > 0) outlineLinks.push({ href: '#section-labs', label: 'Practice Labs' });
      if (data.quickReference && data.quickReference.content) outlineLinks.push({ href: '#section-reference', label: 'Quick Reference' });
      if (data.troubleshooting && data.troubleshooting.length > 0) outlineLinks.push({ href: '#section-troubleshooting', label: 'Troubleshooting' });
      if (data.quiz && data.quiz.length > 0) outlineLinks.push({ href: '#section-quiz', label: 'Quiz' });
      if (data.interviewTips && data.interviewTips.length > 0) outlineLinks.push({ href: '#section-interview', label: 'Interview Tips' });
      if (data.productionTips && data.productionTips.length > 0) outlineLinks.push({ href: '#section-production', label: 'Production Tips' });
      if (data.bestPractices && data.bestPractices.length > 0) outlineLinks.push({ href: '#section-practices', label: 'Best Practices' });
      if (data.enterprisePerspective) outlineLinks.push({ href: '#section-enterprise', label: 'Enterprise' });
      
      outlineArea.innerHTML = outlineLinks.map(function(l) {
        return '<a href="' + l.href + '" class="outline-link">' + l.label + '</a>';
      }).filter(Boolean).join('\n');
      setupOutlineSmoothScroll();
      scrollSpyCleanup = setupOutlineScrollSpy();
    }

    if (contentArea.querySelector('pre code')) {
      if (typeof Prism !== 'undefined') {
        Prism.highlightAllUnder(contentArea);
      }
    }

    // Trigger entrance animations
    requestAnimationFrame(function() {
      requestAnimationFrame(function() {
        const section = contentArea.querySelector('article');
        if (section) section.classList.add('anim-ready');
        if (data.sections) {
          data.sections.forEach((_, idx) => {
            const sec = document.getElementById(`section-${data.id}-${idx}`);
            if (sec) sec.classList.add('anim-ready');
          });
        }
        const syntax = document.getElementById('section-syntax');
        if (syntax) syntax.classList.add('anim-ready');
        const dive = document.getElementById('section-dive');
        if (dive) {
          if (dive.getBoundingClientRect().top < window.innerHeight) {
            dive.classList.add('anim-ready');
          } else {
            const obs = new IntersectionObserver(function(entries) {
              entries.forEach(function(entry) {
                if (entry.isIntersecting) {
                  entry.target.classList.add('anim-ready');
                  obs.unobserve(entry.target);
                }
              });
            }, { threshold: 0.15 });
            obs.observe(dive);
          }
        }
      });
    });

  } catch (error) {
    console.error("Error in loadContent:", error);
    contentArea.innerHTML = `
      <div class="p-6 border-2 border-red-200 dark:border-red-900/30 bg-red-50 dark:bg-red-950/10 rounded-xl text-red-600 dark:text-red-400 text-sm">
        <h3 class="font-bold mb-1">Error Loading Document</h3>
        <p>Failed to load the requested study guide from path: ${path}. Error: ${error.message}</p>
      </div>
    `;
  }
}

function setupOutlineSmoothScroll() {
  const outline = document.getElementById('docs-right-outline');
  if (!outline) return;
  outline.addEventListener('click', function(e) {
    const link = e.target.closest('.outline-link');
    if (!link) return;
    const targetId = link.getAttribute('href');
    const targetElement = document.querySelector(targetId);
    if (targetElement) {
      e.preventDefault();
      targetElement.scrollIntoView({ behavior: 'smooth', block: 'start' });
      document.querySelectorAll('.outline-link').forEach(l => {
        l.classList.toggle('active-outline', l.getAttribute('href') === targetId);
      });
    }
  });
}

function setupOutlineScrollSpy() {
  const links = document.querySelectorAll('.outline-link');
  if (links.length === 0) return null;

  const sections = Array.from(links).map(link => {
    return document.querySelector(link.getAttribute('href'));
  }).filter(Boolean);

  if (sections.length === 0) return null;

  function updateActiveLink() {
    const scrollPosition = window.scrollY + 120;
    
    if ((window.innerHeight + window.scrollY) >= document.documentElement.scrollHeight - 50) {
      links.forEach((link, idx) => link.classList.toggle('active-outline', idx === links.length - 1));
      return;
    }

    let activeSection = null;
    for (let i = 0; i < sections.length; i++) {
      const section = sections[i];
      if (section.offsetTop <= scrollPosition) {
        activeSection = section;
      } else {
        break;
      }
    }

    if (!activeSection && sections.length > 0) {
      activeSection = sections[0];
    }

    if (activeSection) {
      const activeId = activeSection.getAttribute('id');
      links.forEach(link => link.classList.toggle('active-outline', link.getAttribute('href') === `#${activeId}`));
    }
  }

  let tick = false;
  const onScroll = () => {
    if (!tick) {
      requestAnimationFrame(() => {
        updateActiveLink();
        tick = false;
      });
      tick = true;
    }
  };

  window.addEventListener('scroll', onScroll, { passive: true });
  updateActiveLink();

  return () => {
    window.removeEventListener('scroll', onScroll);
  };
}

function escapeHtml(text) {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function showToast(message) {
  const existingToast = document.getElementById('clipboard-toast');
  if (existingToast) {
    existingToast.remove();
  }

  const toast = document.createElement('div');
  toast.id = 'clipboard-toast';
  toast.className = 'fixed bottom-6 right-6 z-50 flex items-center gap-2.5 bg-slate-900/90 dark:bg-slate-800/90 backdrop-blur-md text-white border border-slate-700/50 px-4 py-2.5 rounded-xl shadow-xl text-sm font-sans font-medium transition-all duration-300 transform translate-y-10 opacity-0';
  toast.innerHTML = `
    <span class="material-symbols-outlined text-[18px] text-emerald-400" aria-hidden="true">check_circle</span>
    <span>${message}</span>
  `;

  document.body.appendChild(toast);

  requestAnimationFrame(function() {
    toast.classList.remove('translate-y-10', 'opacity-0');
    toast.classList.add('translate-y-0', 'opacity-100');
  });

  setTimeout(function() {
    toast.classList.remove('translate-y-0', 'opacity-100');
    toast.classList.add('translate-y-10', 'opacity-0');
    setTimeout(function() {
      toast.remove();
    }, 300);
  }, 2200);
}

function copyCode(btn) {
  const codeEl = btn.parentElement.querySelector('code');
  if (!codeEl) return;
  navigator.clipboard.writeText(codeEl.textContent).then(function() {
    const originalHTML = btn.innerHTML;
    btn.innerHTML = '<span class="material-symbols-outlined text-sm text-emerald-500">check</span> Copied!';
    btn.disabled = true;
    showToast('Code copied to clipboard!');
    setTimeout(function() {
      btn.innerHTML = originalHTML;
      btn.disabled = false;
    }, 2000);
  }).catch(function(err) {
    console.error('Failed to copy: ', err);
  });
}
window.copyCode = copyCode;

function addCopyButtonsToPreElements(container) {
  (container || document).querySelectorAll('pre').forEach(function(pre) {
    if (pre.parentElement.classList.contains('group') && pre.parentElement.querySelector('button[onclick*="copyCode"]')) {
      return;
    }
    if (!pre.querySelector('code')) return;
    if (pre.classList.contains('copy-btn-initialized')) return;
    pre.classList.add('copy-btn-initialized');
    
    var wrapper = document.createElement('div');
    wrapper.className = 'border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-800/40 rounded-xl p-5 text-sm leading-relaxed overflow-x-auto relative group';
    
    pre.parentNode.insertBefore(wrapper, pre);
    wrapper.appendChild(pre);
    
    var btn = document.createElement('button');
    btn.className = 'absolute right-3 top-3 opacity-0 group-hover:opacity-100 bg-white dark:bg-slate-900 hover:bg-slate-100 dark:hover:bg-slate-800 border border-slate-200 dark:border-slate-800 px-2.5 py-1.5 rounded-lg text-xs font-sans text-slate-500 transition-all flex items-center gap-1.5';
    btn.innerHTML = '<span class="material-symbols-outlined text-sm" aria-hidden="true">content_copy</span> Copy';
    btn.addEventListener('click', function() {
      copyCode(btn);
    });
    wrapper.insertBefore(btn, pre);
  });
}
window.addCopyButtonsToPreElements = addCopyButtonsToPreElements;

window.addEventListener('DOMContentLoaded', () => {
  const initialHash = window.location.hash || '#linux-history';
  loadContent(initialHash);
  
  // Initialize progress and bookmark views on load
  updateSidebarProgress();
  updateSidebarBookmarks();
  updateSidebarLinksUI();

  // ---- Reading scroll progress bar ----
  (function() {
    var bar = document.getElementById('reading-progress-bar');
    if (!bar) return;
    var ticking = false;
    function updateReadingProgress() {
      var article = document.getElementById('docs-dynamic-content');
      if (!article) { bar.style.width = '0%'; ticking = false; return; }
      var scrollTop = window.scrollY || document.documentElement.scrollTop;
      var articleTop = article.offsetTop || 0;
      var articleHeight = article.scrollHeight || 1;
      var viewportH = window.innerHeight;
      var scrollable = articleTop + articleHeight - viewportH;
      if (scrollable <= 0) { bar.style.width = '100%'; ticking = false; return; }
      var progress = Math.min(100, Math.max(0, ((scrollTop - articleTop + viewportH * 0.1) / scrollable) * 100));
      bar.style.width = progress.toFixed(1) + '%';
      ticking = false;
    }
    window.addEventListener('scroll', function() {
      if (!ticking) { requestAnimationFrame(updateReadingProgress); ticking = true; }
    }, { passive: true });
    // Also reset on hash change (new content loaded)
    window.addEventListener('hashchange', function() {
      setTimeout(updateReadingProgress, 300);
    });
    updateReadingProgress();
  })();
});

window.addEventListener('hashchange', () => {
  loadContent(window.location.hash);
  window.scrollTo({ top: 0, behavior: 'smooth' });
});

window.addEventListener('theme-changed', () => {
  colorizeTags();
  updateSidebarLinksUI();
});

